const VOCAB = [
  // Прикметники — емоційні стани
  {w:"scared",t:"наляканий (зараз)",e:"I'm scared — when something frightens you right now.",topic:"Прикметники"},
  {w:"afraid",t:"боюся / наляканий",e:"I'm afraid he can be late tomorrow.",topic:"Прикметники"},
  {w:"arrogant",t:"зарозумілий",e:"She was too arrogant and never smiled at anyone.",topic:"Прикметники"},
  {w:"disappointed",t:"розчарований",e:"We are disappointed in you.",topic:"Прикметники"},
  {w:"frustrated",t:"засмучений / роздратований",e:"He was too frustrated to continue.",topic:"Прикметники"},
  {w:"annoyed",t:"роздратований",e:"I was annoyed by his phone call.",topic:"Прикметники"},
  {w:"satisfied",t:"задоволений",e:"He was very satisfied with the results.",topic:"Прикметники"},
  {w:"concerned",t:"стурбований",e:"I am very concerned about his results.",topic:"Прикметники"},
  {w:"reliable",t:"надійний",e:"She is very reliable and always keeps her word.",topic:"Прикметники"},
  {w:"responsible",t:"відповідальний",e:"Everyone thinks you are a very responsible person.",topic:"Прикметники"},
  {w:"hypocritical",t:"лицемірний",e:"I punished them for their hypocrisy.",topic:"Прикметники"},
  {w:"conceited",t:"самовдоволений",e:"She became too conceited and rude.",topic:"Прикметники"},
  {w:"cheerful",t:"життєрадісний",e:"They are very brave and cheerful.",topic:"Прикметники"},
  {w:"selfish",t:"егоїстичний",e:"He refused to help her because she is too selfish.",topic:"Прикметники"},
  {w:"pale",t:"блідий",e:"Everyone was very pale because they were afraid.",topic:"Прикметники"},
  {w:"slim",t:"струнка",e:"She is slim and good-looking.",topic:"Прикметники"},
  {w:"gorgeous",t:"чудовий / гарний",e:"She looks gorgeous in that dress.",topic:"Прикметники"},
  // Дієслова + інфінітив
  {w:"pretend to",t:"вдавати / прикидатися",e:"He pretended to be sick.",topic:"Дієслова + інфінітив"},
  {w:"decide to",t:"вирішити (прийняти рішення)",e:"She decided to leave early.",topic:"Дієслова + інфінітив"},
  {w:"refuse to",t:"відмовитися",e:"He refused to help her.",topic:"Дієслова + інфінітив"},
  {w:"agree to",t:"погодитися",e:"They agreed to come.",topic:"Дієслова + інфінітив"},
  {w:"fail to",t:"не вийшло / не змогти",e:"He failed to pass the exam.",topic:"Дієслова + інфінітив"},
  {w:"manage to",t:"вдалося зробити",e:"She managed to finish on time.",topic:"Дієслова + інфінітив"},
  {w:"hope to",t:"сподіватися",e:"I hope to see you soon.",topic:"Дієслова + інфінітив"},
  {w:"plan to",t:"планувати",e:"We plan to travel next month.",topic:"Дієслова + інфінітив"},
  {w:"try to",t:"намагатися",e:"She tried to be calm.",topic:"Дієслова + інфінітив"},
  {w:"forget to",t:"забути (зробити)",e:"She forgot to call him.",topic:"Дієслова + інфінітив"},
  {w:"learn to",t:"навчитися",e:"She learned to swim at the age of five.",topic:"Дієслова + інфінітив"},
  // Дієслова загальні
  {w:"admire for",t:"захоплюватися (чимось)",e:"He admires her for her beauty and kindness.",topic:"Дієслова загальні"},
  {w:"blame for",t:"звинувачувати",e:"I don't blame you for this.",topic:"Дієслова загальні"},
  {w:"rely on",t:"покладатися на",e:"My colleagues rely on me.",topic:"Дієслова загальні"},
  {w:"count on",t:"розраховувати на",e:"I count on you.",topic:"Дієслова загальні"},
  {w:"complain about",t:"скаржитися на",e:"Nobody ever complains about their work.",topic:"Дієслова загальні"},
  {w:"envy",t:"заздрити",e:"I envy you — you are so lucky.",topic:"Дієслова загальні"},
  {w:"wink at",t:"підморгувати",e:"She smiled and winked at him.",topic:"Дієслова загальні"},
  {w:"punish for",t:"покарати за",e:"I punished them for their hypocrisy.",topic:"Дієслова загальні"},
  {w:"stare at",t:"витріщитися на",e:"Everyone stared at him because of his new suit.",topic:"Дієслова загальні"},
  {w:"divorce",t:"розлучитися",e:"She will divorce him because she doesn't love him.",topic:"Дієслова загальні"},
  {w:"boast about",t:"хвалитися",e:"He always boasts about his car.",topic:"Дієслова загальні"},
  {w:"investigate",t:"розслідувати / досліджувати",e:"They investigated the case for months.",topic:"Дієслова загальні"},
  {w:"assess",t:"оцінювати",e:"We need to assess the situation.",topic:"Дієслова загальні"},
  {w:"solve",t:"вирішувати (проблему)",e:"We need to solve this problem quickly.",topic:"Дієслова загальні"},
  // Конструкції
  {w:"would like",t:"хотілося б",e:"He would like to be here with us.",topic:"Конструкції"},
  {w:"wouldn't like",t:"не хотілося б",e:"She wouldn't like to know too much.",topic:"Конструкції"},
  {w:"be going to",t:"збиратися (зробити)",e:"I am going to travel next week.",topic:"Конструкції"},
  {w:"in order to",t:"щоб (мета)",e:"He works hard in order to earn well.",topic:"Конструкції"},
  {w:"in order not to",t:"щоб не",e:"She took a taxi in order not to be late.",topic:"Конструкції"},
  {w:"like the way",t:"подобається, як...",e:"I like the way she teaches English.",topic:"Конструкції"},
  {w:"know how to",t:"знаю, як...",e:"Do you know how to drive?",topic:"Конструкції"},
  {w:"so am I / so do I",t:"я теж (після стверджувального)",e:"I am tired. — So am I.",topic:"Конструкції"},
  {w:"neither do I / neither am I",t:"я теж ні (після заперечного)",e:"She doesn't smoke. — Neither do I.",topic:"Конструкції"},
  // Сполучники
  {w:"both … and …",t:"і … і …",e:"She both sings and dances well.",topic:"Сполучники"},
  {w:"either … or …",t:"або … або …",e:"Either you go or I go.",topic:"Сполучники"},
  {w:"neither … nor …",t:"ні … ні …",e:"He has neither money nor time.",topic:"Сполучники"},
  {w:"not only … but also …",t:"не тільки … але й …",e:"He is not only responsible but also kind.",topic:"Сполучники"},
  {w:"frankly speaking",t:"відверто кажучи",e:"Frankly speaking, I was not ready.",topic:"Сполучники"},
  {w:"the matter is that",t:"справа в тому, що",e:"The matter is that we don't have enough time.",topic:"Сполучники"},
  {w:"nevertheless",t:"тим не менш",e:"Nevertheless, he helped us.",topic:"Сполучники"},
  {w:"besides",t:"крім того",e:"Besides, they often travel together.",topic:"Сполучники"},
  {w:"according to",t:"за словами / згідно з",e:"According to him, we will be late.",topic:"Сполучники"},
  {w:"thanks to",t:"завдяки",e:"Thanks to him, she eats less bread.",topic:"Сполучники"},
  {w:"because of",t:"через / із-за",e:"Because of the rain, we stayed home.",topic:"Сполучники"},
  {w:"as for",t:"що стосується",e:"As for me, I prefer tea.",topic:"Сполучники"},
  {w:"unlike",t:"на відміну від",e:"Unlike her sister, she is very quiet.",topic:"Сполучники"},
  // Іменники
  {w:"solution",t:"рішення (задачі / проблеми)",e:"We need an efficient solution.",topic:"Іменники"},
  {w:"gratitude",t:"вдячність",e:"He expressed his gratitude.",topic:"Іменники"},
  {w:"concern",t:"занепокоєння / тривога",e:"My main concern is that he will be very busy.",topic:"Іменники"},
  {w:"achievement",t:"досягнення",e:"I am proud of this achievement.",topic:"Іменники"},
  {w:"challenge",t:"виклик / складне завдання",e:"The biggest challenge was the tight deadline.",topic:"Іменники"},
  {w:"opportunity",t:"можливість",e:"This is a great opportunity to grow.",topic:"Іменники"},
  {w:"experience",t:"досвід",e:"She didn't have the necessary experience.",topic:"Іменники"},
  {w:"strength",t:"сильна сторона",e:"My main strength is attention to detail.",topic:"Іменники"},
  {w:"weakness",t:"слабка сторона",e:"I tend to focus too much on details — that's my weakness.",topic:"Іменники"},
  {w:"deadline",t:"дедлайн / кінцевий термін",e:"We need to meet the deadline.",topic:"Іменники"},
  {w:"feedback",t:"зворотний зв'язок",e:"I always ask for feedback after the presentation.",topic:"Іменники"},
  {w:"update",t:"оновлення / повідомити нове",e:"Could you give me an update on this task?",topic:"Іменники"},
  {w:"schedule",t:"розклад / план",e:"Let me check my schedule.",topic:"Іменники"},
  // Розмовні та сучасні
  {w:"actually",t:"насправді / власне кажучи",e:"Actually, I think it's a great idea.",topic:"Розмовні"},
  {w:"basically",t:"загалом / по суті",e:"Basically, we need to restart the service.",topic:"Розмовні"},
  {w:"apparently",t:"схоже / судячи з усього",e:"Apparently, nobody told him about the meeting.",topic:"Розмовні"},
  {w:"eventually",t:"врешті-решт / з часом",e:"Eventually, we found a better solution.",topic:"Розмовні"},
  {w:"currently",t:"зараз / на даний момент",e:"I am currently working on a new feature.",topic:"Розмовні"},
  {w:"obviously",t:"очевидно",e:"Obviously, we need to fix this before the release.",topic:"Розмовні"},
  {w:"definitely",t:"точно / безумовно",e:"I can definitely recommend this series.",topic:"Розмовні"},
  {w:"I mean",t:"я маю на увазі",e:"It was difficult — I mean, really difficult.",topic:"Розмовні"},
  {w:"you know",t:"знаєш / розумієш (пауза)",e:"It was, you know, a really tough project.",topic:"Розмовні"},
  {w:"I guess",t:"мабуть / я думаю",e:"I guess we need more time for this.",topic:"Розмовні"},
  {w:"sort of / kind of",t:"щось на кшталт / певною мірою",e:"It's sort of a wrapper around the API.",topic:"Розмовні"},
  {w:"to be honest",t:"чесно кажучи",e:"To be honest, I wasn't ready for that question.",topic:"Розмовні"},
  {w:"that's why",t:"ось чому / тому",e:"That's why I decided to set up monitoring.",topic:"Розмовні"},
  {w:"in general",t:"загалом",e:"In general, the project went well.",topic:"Розмовні"},
  {w:"at the moment",t:"зараз / на цей момент",e:"At the moment I am working on performance optimization.",topic:"Розмовні"},
  {w:"as soon as possible",t:"якомога швидше",e:"I will send you the report as soon as possible.",topic:"Розмовні"},
  {w:"in any case",t:"у будь-якому разі",e:"In any case, we should test it before deploying.",topic:"Розмовні"},
  {w:"on the one hand… on the other hand",t:"з одного боку… з іншого боку",e:"On the one hand it's risky, on the other hand it's a good opportunity.",topic:"Розмовні"},
  {w:"as far as I know",t:"наскільки я знаю",e:"As far as I know, the release is planned for Friday.",topic:"Розмовні"},
  {w:"however",t:"однак / проте",e:"The task was difficult. However, we managed to complete it.",topic:"Розмовні"},
  {w:"although",t:"хоча / незважаючи на те що",e:"Although it took time, the result was worth it.",topic:"Розмовні"},
  {w:"while",t:"поки / тоді як",e:"While she was away, things changed a lot.",topic:"Розмовні"},
  {w:"used to",t:"раніше робив (але вже ні)",e:"I used to work with Angular before switching to React.",topic:"Розмовні"},
  {w:"tend to",t:"схильний / зазвичай роблю",e:"I tend to spend too much time on details.",topic:"Розмовні"},
  {w:"manage to",t:"вдається / вийшло",e:"I managed to finish the task before the deadline.",topic:"Розмовні"},
  // IT — для інтерв'ю та розмови про роботу
  {w:"wrap / unwrap",t:"обгортка / розгортати (дані)",e:"We need to wrap the data before sending.",topic:"IT"},
  {w:"an efficient solution",t:"ефективне рішення",e:"This is an efficient solution to the problem.",topic:"IT"},
  {w:"in accordance with",t:"відповідно до",e:"We act in accordance with the requirements.",topic:"IT"},
  {w:"to work on a project",t:"працювати над проектом",e:"I am currently working on a large project.",topic:"IT"},
  {w:"to perform refactoring",t:"робити рефакторинг",e:"We decided to perform refactoring of the main module.",topic:"IT"},
  {w:"to assign a task",t:"призначити завдання (комусь)",e:"The manager assigned the task to a senior developer.",topic:"IT"},
  {w:"to miss a deadline",t:"пропустити дедлайн",e:"We can't afford to miss this deadline.",topic:"IT"},
  {w:"to identify",t:"визначати / виявляти",e:"I managed to identify the root cause of the issue.",topic:"IT"},
  {w:"to provide",t:"надавати",e:"Can you provide more details about the requirements?",topic:"IT"},
  {w:"to complete",t:"завершити / виконати",e:"I need two more days to complete this task.",topic:"IT"},
  {w:"to deploy",t:"задеплоїти / випустити",e:"We deployed the new version to production yesterday.",topic:"IT"},
  {w:"to debug",t:"шукати і виправляти помилки",e:"It took me hours to debug that issue.",topic:"IT"},
  {w:"to review (code)",t:"перевіряти (код)",e:"Could you review my pull request?",topic:"IT"},
  {w:"to maintain",t:"підтримувати / супроводжувати",e:"I am responsible for maintaining the frontend codebase.",topic:"IT"},
  {w:"to set up",t:"налаштовувати / встановлювати",e:"I set up Sentry for error monitoring.",topic:"IT"},
  {w:"to speed up",t:"прискорювати",e:"These changes speeded up the page loading by 40%.",topic:"IT"},
  {w:"to reduce / decrease",t:"скоротити / зменшити",e:"We managed to reduce the number of errors by 60%.",topic:"IT"},
  {w:"codebase",t:"кодова база",e:"The codebase was very hard to maintain.",topic:"IT"},
  {w:"performance",t:"продуктивність",e:"We improved the performance of the application.",topic:"IT"},
  {w:"observability",t:"спостережуваність (моніторинг системи)",e:"We set up observability tools such as Sentry and Honeycomb.",topic:"IT"},
  {w:"monitoring tools",t:"інструменти моніторингу",e:"Monitoring tools help you detect issues early.",topic:"IT"},
  {w:"pull request (PR)",t:"пул-реквест (запит на злиття коду)",e:"Please approve my pull request when you have time.",topic:"IT"},
  {w:"sprint",t:"спринт (ітерація в Scrum)",e:"We plan our work in two-week sprints.",topic:"IT"},
  {w:"stakeholder",t:"зацікавлена сторона",e:"We need to present the results to the stakeholders.",topic:"IT"},
  {w:"on time",t:"вчасно (точно в строк)",e:"The project was delivered on time.",topic:"IT"},
  {w:"in time",t:"заздалегідь / встигнути",e:"We finished the testing in time before the release.",topic:"IT"},
  {w:"urgent",t:"терміновий",e:"This bug is urgent — it affects all users.",topic:"IT"},
  {w:"once a month / twice a week",t:"раз на місяць / двічі на тиждень",e:"We have a sync meeting twice a week.",topic:"IT"},
  {w:"all day long",t:"цілий день",e:"I was debugging all day long.",topic:"IT"},
  {w:"a fixed monthly rate",t:"фіксована ставка на місяць",e:"I work on a fixed monthly rate.",topic:"IT"},
  {w:"penalty",t:"штраф / санкція",e:"There is a penalty for missing the deadline.",topic:"IT"},
  {w:"mentoring / to mentor",t:"менторство / бути ментором",e:"My duties include mentoring junior developers.",topic:"IT"},
  {w:"responsibilities / duties",t:"обов'язки",e:"My responsibilities include code review and planning.",topic:"IT"},
  {w:"architectural solution",t:"архітектурне рішення",e:"I take part in planning of architectural solutions.",topic:"IT"},
  {w:"lazy loading",t:"ліниве завантаження",e:"I implemented lazy loading to improve performance.",topic:"IT"},
  {w:"container orchestration",t:"оркестрація контейнерів",e:"Kubernetes is a container orchestrator.",topic:"IT"},
  // Схожі слова
  {w:"SOAP",t:"мило (не суп!)",e:"I need soap to wash my hands.",topic:"Схожі слова"},
  {w:"SOUP",t:"суп (не мило!)",e:"She made delicious soup for dinner.",topic:"Схожі слова"},
];

const SENTENCES = [
  {ua:"Я думаю, що буду на роботі о 8 і не запізнюся.",en:"I think I will be at work by 8 and I won't be late.",set:"Set 1"},
  {ua:"Ніхто не сумує за ним, бо ніхто його не любить.",en:"Nobody misses him because nobody likes him.",set:"Set 1"},
  {ua:"Він хотів би бути тут, і він хотів би нам допомогти.",en:"He would like to be here and he would like to help us.",set:"Set 1"},
  {ua:"Вона б не хотіла знати забагато, але хотіла б бути розумною.",en:"She wouldn't like to know too much but she would like to be smart.",set:"Set 1"},
  {ua:"Мені б не хотілося тебе бачити, бо ти мені не подобаєшся.",en:"I wouldn't like to see you because I don't like you.",set:"Set 1"},
  {ua:"Мій приятель часто дивився на свою сусідку і захоплювався нею.",en:"My friend often looked at his neighbour and admired her.",set:"Set 1"},
  {ua:"Ніхто ніколи не буде посміхатися і підморгувати їй на уроці.",en:"Nobody will ever smile and wink at her during the lesson.",set:"Set 1"},
  {ua:"Вона була надто зарозуміла і ніколи нікому не посміхалася.",en:"She was too arrogant and never smiled at anyone.",set:"Set 2"},
  {ua:"Ми розчаровані у вас, тому ми б не хотіли дотримуватися ваших інструкцій.",en:"We are disappointed in you, so we wouldn't like to follow your instructions.",set:"Set 2"},
  {ua:"У неї не було необхідного досвіду, тому її не найняли.",en:"She didn't have the necessary experience, so they didn't hire her.",set:"Set 2"},
  {ua:"Він захоплюється нею за її красу і доброту, крім того він пишається нею.",en:"He admires her for her beauty and kindness, besides he is proud of her.",set:"Set 2"},
  {ua:"Я покарав їх за лицемірство, тому вони мене ненавидять.",en:"I punished them for their hypocrisy, so they hate me.",set:"Set 2"},
  {ua:"Він відмовиться допомагати їй, бо вона надто егоїстична.",en:"He will refuse to help her because she is too selfish.",set:"Set 2"},
  {ua:"Я не звинувачую вас у легковажності. Справа в тому, що вам бракує терпіння.",en:"I don't blame you for your frivolity. The matter is that you don't have enough patience.",set:"Set 2"},
  {ua:"Відверто кажучи, я не був готовий до цього, тому мене дратував його дзвінок.",en:"Frankly speaking, I was not ready for it, so I was annoyed by his call.",set:"Set 2"},
  {ua:"Вона забула йому відповісти, бо була дуже зайнята.",en:"She forgot to answer him because she was very busy.",set:"Set 3"},
  {ua:"У нього більше нема терпіння — він надто розчарований у ній.",en:"He has no patience left — he is too disappointed in her.",set:"Set 3"},
  {ua:"Я розраховую на вас. Всі кажуть, що ви дуже відповідальна людина.",en:"I count on you. Everyone says you are a very responsible person.",set:"Set 3"},
  {ua:"Ніхто ніколи не скаржиться на свою роботу, бо всі дуже успішні.",en:"Nobody ever complains about their work because everyone is very successful.",set:"Set 3"},
  {ua:"Подруга моєї мами відмовилася купувати нову машину своєму синові, бо він лінивий.",en:"My mother's friend refused to buy her son a new car because he is lazy.",set:"Set 3"},
  {ua:"Вони відмовлять йому, бо в нього не буде жодного доказу.",en:"They will refuse him because he won't have a single piece of evidence.",set:"Set 4"},
  {ua:"Всі витріщилися на нього, бо на ньому був новий костюм.",en:"Everyone stared at him because he was wearing a new suit.",set:"Set 4"},
  {ua:"Він був дуже схвильований щодо майбутньої зустрічі.",en:"He was very excited about the upcoming meeting.",set:"Set 4"},
  {ua:"У всіх було багато часу, щоб підготуватися.",en:"Everyone had plenty of time in order to prepare.",set:"Set 4"},
  {ua:"У дитинстві вона і співала, і танцювала добре, тому стала відомою співачкою.",en:"As a child she both sang and danced well, so she became a famous singer.",set:"Set 5"},
  {ua:"Він не тільки відповідальний, але й порядний, тому всі його поважають.",en:"He is not only responsible but also decent, so everyone respects him.",set:"Set 5"},
  {ua:"У них немає ні роботи, ні грошей, бо вони надто самовдоволені.",en:"They have neither a job nor money because they are too conceited.",set:"Set 5"},
  {ua:"Завдяки йому вона їсть мало хліба. Справа в тому, що вона закохалася в нього.",en:"Thanks to him she eats little bread. The matter is that she fell in love with him.",set:"Set 5"},
  {ua:"Я погано виходжу на фотографіях. Вона теж.",en:"I don't look good in photos. Neither does she.",set:"Set 6"},
  {ua:"Вона не готова сьогодні. Ми теж. Вчора ми добре провели час — ми і співали, і танцювали.",en:"She is not ready today. Neither are we. Yesterday we had a great time — we both sang and danced.",set:"Set 6"},
  {ua:"Вона завжди робить нотатки під час лекції. Ми теж. А він не робить.",en:"She always takes notes during the lecture. So do we. But he doesn't.",set:"Set 6"},
  {ua:"Вона часто порівнює його зі своїм другом, хоча йому це не подобається. Мені теж.",en:"She often compares him to her friend, although he doesn't like it. Neither do I.",set:"Set 6"},
  {ua:"З одного боку, він звинуватив її у своїх проблемах, але з іншого боку вона завжди була добра до нього.",en:"On the one hand he blamed her for his problems, but on the other hand she was always kind to him.",set:"Set 6"},
  {ua:"In order to get up early he set the alarm.",en:"Щоб встати рано, він поставив будильник.",set:"Практика конструкцій"},
  {ua:"In order not to be late she took a taxi.",en:"Щоб не запізнитися, вона взяла таксі.",set:"Практика конструкцій"},
  {ua:"She decided to go in order to save money.",en:"Вона вирішила піти, щоб заощадити гроші.",set:"Практика конструкцій"},
  {ua:"I like the way she teaches English.",en:"Мені подобається, як вона викладає англійську.",set:"Практика конструкцій"},
  {ua:"Do you know how to drive?",en:"Ти вмієш водити машину?",set:"Практика конструкцій"},
  {ua:"Why did he fail to help?",en:"Чому йому не вдалося допомогти?",set:"Практика конструкцій"},
  {ua:"She managed to get a day off.",en:"Їй вдалося взяти вихідний.",set:"Практика конструкцій"},
  {ua:"Is she going to have a date?",en:"Вона збирається на побачення?",set:"Практика конструкцій"},
  {ua:"Why did you choose to work in IT?",en:"Чому ви обрали роботу в IT?",set:"IT інтерв'ю"},
  {ua:"What are your current responsibilities?",en:"Які ваші поточні обов'язки?",set:"IT інтерв'ю"},
  {ua:"Are you trying to learn anything new at the moment?",en:"Ви зараз намагаєтеся чомусь навчитися?",set:"IT інтерв'ю"},
  {ua:"Where do you see yourself in the future?",en:"Ким ви бачите себе в майбутньому?",set:"IT інтерв'ю"},
];

// Правила граматики згруповані за категоріями
const GRAMMAR_GROUPS = [
  {
    group: "Конструкції",
    rules: [
      {
        title: "would like / wouldn't like",
        tag: "Конструкція",
        explanation: "Ввічливе бажання. Форма НЕ ЗМІНЮЄТЬСЯ — завжди однакова для всіх осіб.\n\nwould like = хотілося б\nwouldn't like = не хотілося б\nwould you like…? = питання",
        examples: [
          "He would like to be here. (він — форма та сама!)",
          "She wouldn't like to know too much.",
          "Would you like to have dinner?",
          "What would you like to eat?",
          "Where would you like to go?"
        ]
      },
      {
        title: "be going to",
        tag: "Майбутній час",
        explanation: "Виражає ЗАПЛАНОВАНУ дію, яка точно відбудеться, або дію очевидну з поточної ситуації.\n\nВажливо: НЕ використовується разом з will!",
        examples: [
          "I am going to travel next week. (план)",
          "Is she going to be there? (заплановано?)",
          "I'm not going to be away. (точно не буду)",
          "It's not going to be cold today. (очевидно з ситуації)",
          "Are you going to get married? (план)",
        ]
      },
      {
        title: "in order to / in order not to",
        tag: "Конструкція",
        explanation: "in order to = щоб (мета)\nin order not to = щоб не (уникнути)\n\nМожна скоротити до просто 'to'",
        examples: [
          "He needs to work a lot in order to earn well.",
          "She took a taxi in order not to be late.",
          "She decided to go in order to save money.",
          "He refused in order not to miss the flight.",
          "I don't have enough time to convince them. (скорочена форма)"
        ]
      },
      {
        title: "like the way / know how to",
        tag: "Конструкція",
        explanation: "like the way = подобається, ЯК хтось щось робить\nknow how to = знати ЯК щось робити (вміння)",
        examples: [
          "I like the way she teaches English.",
          "I like the way he works.",
          "I don't like the way you behave.",
          "Do you know how to drive?",
          "Does anybody know how to dance?",
          "Why doesn't she know how to cook?"
        ]
      },
    ]
  },
  {
    group: "Граматика",
    rules: [
      {
        title: "Possessive Case",
        tag: "Присвійний відмінок",
        explanation: "Одушевлені → додаємо 's\nНеодушевлені → прийменник 'of'",
        examples: [
          "the girl's name (одушевлене → 's)",
          "the cat's tail (одушевлене → 's)",
          "the back of the car (неодушевлене → of)",
          "the roof of the house (неодушевлене → of)",
          "yesterday's newspaper (часовий вираз → 's)",
          "a friend of mine (= my friend)",
          "a friend of my sister's (= my sister's friend)"
        ],
        table: [
          ["Тип","Правило","Приклад"],
          ["Одушевлене","+ 's","the girl's name"],
          ["Неодушевлене","of + noun","the roof of the house"],
          ["Організація/місце","'s OR of","the world's population"],
          ["Часовий","'s","yesterday's newspaper"],
        ]
      },
      {
        title: "Verbs + Infinitive",
        tag: "Дієслова + інфінітив",
        explanation: "Ці дієслова вимагають інфінітив (to + verb) наступного дієслова:\npretend, decide, refuse, agree, fail, manage, try, hope, plan, learn, forget",
        examples: [
          "He pretended to be sick.",
          "She decided to go to London.",
          "He refused to study.",
          "She managed to get a day off.",
          "Why did he fail to help?",
          "She forgot to call him.",
          "He hoped to see her.",
          "She tried to be calm."
        ]
      },
      {
        title: "Two Verbs in a Row",
        tag: "Правило",
        explanation: "Коли в реченні два дієслова підряд:\n→ ПЕРШЕ дієслово змінюється (приймає всі форми часу)\n→ ДРУГЕ залишається в базовій формі (інфінітив)",
        examples: [
          "She WANTS to go. (wants — змінено, go — базова форма)",
          "He DECIDED to leave. (decided — минулий час, leave — база)",
          "They REFUSED to answer. (refused — змінено)",
          "She MANAGED to finish. (managed — змінено)"
        ]
      },
      {
        title: "Adjectives + Prepositions",
        tag: "Прикметники з прийменниками",
        explanation: "Багато прикметників вимагають певний прийменник. Їх потрібно запам'ятовувати як словосполучення.",
        examples: [
          "disappointed IN somebody (розчарований в комусь)",
          "satisfied WITH something (задоволений чимось)",
          "afraid OF something (боїться чогось)",
          "proud OF somebody (пишається кимось)",
          "excited ABOUT something (схвильований чимось)",
          "concerned ABOUT something (стурбований чимось)",
          "ready FOR something (готовий до чогось)"
        ]
      },
      {
        title: "Question Words Structure",
        tag: "Питальні слова",
        explanation: "Спеціальне питання:\nWHO / WHAT / WHERE / WHEN / WHY / HOW + допоміжне дієслово + підмет + присудок",
        examples: [
          "Where does she live?",
          "When did he arrive?",
          "Why are you late?",
          "How many books does she have?",
          "How happy is he?",
          "Who is coming to the party?"
        ]
      },
      {
        title: "Reflexive Pronouns",
        tag: "Зворотні займенники",
        explanation: "myself, yourself, himself, herself, itself, ourselves, yourselves, themselves\n\nby oneself = сам, самостійно (без допомоги)",
        examples: [
          "She made herself a new suit.",
          "He bought the car by himself. (сам, без допомоги)",
          "Look at yourself!",
          "Don't hurt yourself!",
          "They did it by themselves.",
          "Help yourself! (частуйтеся)"
        ]
      },
    ]
  },
  {
    group: "Лексика та зв'язки",
    rules: [
      {
        title: "scared vs afraid",
        tag: "Лексика",
        explanation: "scared — страх у конкретний момент (прямо зараз)\nafraid — загалом, або припущення про майбутнє",
        examples: [
          "I'm scared! (щось налякало прямо зараз, під час фільму)",
          "I'm afraid he can be late tomorrow (припущення — afraid ✓)",
          "I'm scared of spiders (постійний страх — обидва варіанти)",
          "Are you afraid of the dark? (загальне — afraid ✓)"
        ]
      },
      {
        title: "Agreement: So / Neither",
        tag: "Згода / незгода",
        explanation: "Після СТВЕРДЖУВАЛЬНОГО: So + допом. дієслово + підмет (= я теж)\nПісля ЗАПЕРЕЧНОГО: Neither + допом. дієслово + підмет (= я теж ні)\n\nАльтернатива для заперечного: ... not ... either",
        examples: [
          "I am tired. — So am I. (я теж втомився)",
          "She is happy. — So am I. (я теж щасливий)",
          "She doesn't smoke. — Neither do I. (я теж не курю)",
          "He can't swim. — Neither can she. (вона теж не вміє)",
          "I am not surprised. — I am not surprised either. (альтернатива)",
          "She is ready. But he isn't. (а він ні — протиставлення)"
        ]
      },
      {
        title: "Connectors: Both/Either/Neither",
        tag: "Сполучні слова",
        explanation: "both … and … = і … і … (обидва)\neither … or … = або … або …\nneither … nor … = ні … ні …\nnot only … but also … = не тільки … але й …",
        examples: [
          "She both sings and dances well.",
          "Either you go or I go.",
          "He has neither money nor time.",
          "He is not only responsible but also kind.",
          "We will both work and study hard next year."
        ]
      },
      {
        title: "Discourse Markers",
        tag: "Фрази-зв'язки",
        explanation: "Слова та вирази для зв'язку речень і структурування мови",
        examples: [
          "Frankly speaking, I was not ready. (відверто кажучи)",
          "The matter is that we have no time. (справа в тому, що)",
          "On the one hand… on the other hand… (з одного / іншого боку)",
          "Nevertheless, he helped us. (тим не менш)",
          "Besides, they often travel. (крім того)",
          "According to him, we will be late. (за його словами)",
          "Thanks to her, everything went well. (завдяки їй)",
          "Unfortunately, he missed the flight. (на жаль)"
        ]
      },
    ]
  }
];

// Плаский список для зворотної сумісності
const GRAMMAR = GRAMMAR_GROUPS.flatMap(g => g.rules);

const QUIZ_DATA = [
  {q:"Обери правильний варіант для 'хвіст кішки':", opts:["of the cat tail","the cat tail","the cat's tail","cat of tail"], correct:2, note:"Одушевлені іменники → 's. Кішка — жива, тому the cat's tail.", topic:"Possessive Case"},
  {q:"Як сказати 'дах будинку'?", opts:["the house's roof","the roof of the house","the house roof","roof's of the house"], correct:1, note:"Неодушевлені іменники → of. Будинок — неживий, тому the roof OF the house.", topic:"Possessive Case"},
  {q:"'Я злякався прямо зараз!' — правильний варіант?", opts:["I'm afraid!","I'm scared!","I afraid!","I'm fear!"], correct:1, note:"scared = страх у конкретний момент (прямо зараз). afraid = загалом або припущення.", topic:"scared vs afraid"},
  {q:"'Боюся, він запізниться завтра' — правильний варіант?", opts:["I'm scared he will be late","I'm afraid he will be late","I am fear he will be late","I'm afraid of he late"], correct:1, note:"afraid = припущення/загальне. Для майбутніх подій або загального страху використовуємо afraid.", topic:"scared vs afraid"},
  {q:"Обери правильну форму 'would like' для 'він':", opts:["He wills like to go","He would likes to go","He would like to go","He will likes to go"], correct:2, note:"would like НЕ змінюється! Завжди одна форма для всіх осіб: He/She/They — would like.", topic:"would like"},
  {q:"'Вона збирається на вечірку' (заплановано):", opts:["She will go to the party","She goes to the party","She is going to go to the party","She going to party"], correct:2, note:"be going to = запланована дія. Is going (she) + to + дієслово.", topic:"be going to"},
  {q:"'Щоб не запізнитися, вона взяла таксі':", opts:["in order to not late","in order not to be late","not in order to be late","in order to be not late"], correct:1, note:"in order NOT TO + інфінітив = щоб не. Порядок: not to завжди разом.", topic:"in order to"},
  {q:"'Мені подобається, ЯК він працює' — як сказати?", opts:["I like how he works","I like that way he works","I like the way he works","I like which he works"], correct:2, note:"like the way = подобається, ЯК хтось щось робить. Саме 'the way', не 'how'.", topic:"like the way"},
  {q:"'Ти вмієш водити?' — як запитати?", opts:["Do you know how drive?","Do you know to drive?","Do you know how to drive?","Do you know driving?"], correct:2, note:"know how to + інфінітив. Конструкція: знати ЯК щось робити.", topic:"know how to"},
  {q:"'Він прикинувся, що захворів':", opts:["He pretended to be sick","He pretended being sick","He pretend to be sick","He was pretending sick"], correct:0, note:"pretend + to + інфінітив. Це одне з дієслів групи Verbs + Infinitive.", topic:"Verbs + Infinitive"},
  {q:"'Їй вдалося взяти вихідний':", opts:["She managed getting a day off","She managed to get a day off","She managed get a day off","She managed to getting a day off"], correct:1, note:"manage + to + інфінітив. Вся група: pretend/decide/refuse/agree/fail/manage/try/hope/plan/learn/forget — всі з 'to'.", topic:"Verbs + Infinitive"},
  {q:"'Я теж втомився' після 'She is tired':", opts:["Neither am I","So do I","So am I","I am too also"], correct:2, note:"Після стверджувального з be: So am/is/are + I/he/she. She IS tired → So AM I.", topic:"Agreement"},
  {q:"'Я теж не курю' після 'She doesn't smoke':", opts:["So do I","Neither do I","I too not","Me neither do"], correct:1, note:"Після ЗАПЕРЕЧНОГО: Neither + допоміжне дієслово + підмет. Doesn't → do (базова).", topic:"Agreement"},
  {q:"'Вона і співає, і танцює добре':", opts:["Either she sings or dances well","Neither does she sing nor dance","She both sings and dances well","Not only does she sing but also dance well"], correct:2, note:"both … and … = і … і … (обидві дії виконуються). She BOTH sings AND dances well. Не плутай з either/or (вибір між двома).", topic:"Connectors"},
  {q:"'У нього немає ні грошей, ні часу':", opts:["He has both no money and time","He has either no money or time","He has neither money nor time","He not has money and time"], correct:2, note:"neither … nor … = ні … ні … (жодного з двох).", topic:"Connectors"},
  {q:"Перше чи друге дієслово змінюється в реченні?", opts:["Обидва змінюються","Тільки перше","Тільки друге","Жодне"], correct:1, note:"Перше дієслово бере на себе все (змінюється за часом/особою). Друге залишається в базовій формі: She WANTS to go.", topic:"Two Verbs"},
  {q:"'Розчарований В комусь' — який прийменник?", opts:["disappointed about","disappointed with","disappointed in","disappointed of"], correct:2, note:"disappointed IN somebody. Прийменники з прикметниками потрібно запам'ятовувати! Satisfied WITH, afraid OF, proud OF.", topic:"Adjectives + Prepositions"},
  {q:"Reflexive: 'Він купив машину сам, без допомоги':", opts:["He bought the car himself","He bought the car by himself","He bought by himself car","He by himself bought car"], correct:1, note:"BY oneself = сам, без чиєїсь допомоги. Просто 'himself' означає 'для себе/собі'.", topic:"Reflexive Pronouns"},

  // --- would like ---
  {q:"'Я б хотів поговорити з менеджером':", opts:["I will like to speak to the manager","I would like to speak to the manager","I would likes to speak to the manager","I like to speak to the manager"], correct:1, note:"would like НЕ змінюється. Завжди: would like + to + інфінітив.", topic:"would like"},
  {q:"'Вони б хотіли відвідати Париж' — правильна форма:", opts:["They would likes to visit Paris","They will like to visit Paris","They would like to visit Paris","They would like visit Paris"], correct:2, note:"would like — однакова форма для всіх осіб: I/you/he/she/they would like.", topic:"would like"},
  {q:"'Ти б хотів трохи кави?' — як запитати:", opts:["Would you like some coffee?","Will you like some coffee?","Do you would like coffee?","You would like coffee?"], correct:0, note:"Would you like…? = ввічливе запитання-пропозиція. Допоміжне would стоїть на початку.", topic:"would like"},
  {q:"'Вона б не хотіла бути на його місці':", opts:["She not would like to be in his place","She wouldn't like to be in his place","She wouldn't likes to be in his place","She will not like to be in his place"], correct:1, note:"wouldn't like = wouldn't + like (заперечення). Форма однакова для всіх осіб.", topic:"would like"},
  {q:"'Мої батьки б хотіли познайомитися з тобою':", opts:["My parents would like to meet you","My parents will like to meet you","My parents would likes to meet you","My parents would like meet you"], correct:0, note:"would like + to + інфінітив. Не додай -s після would like для третьої особи.", topic:"would like"},
  {q:"'Що б ви хотіли з'їсти?' — правильний варіант:", opts:["What will you like to eat?","What would you like to eat?","What you would like to eat?","What would you like eat?"], correct:1, note:"What would you like to eat? — класичне ввічливе запитання в ресторані.", topic:"would like"},
  {q:"'Він би не хотів знову починати з нуля':", opts:["He won't like to start over","He wouldn't like to start over","He wouldn't likes to start over","He would not likes to start over"], correct:1, note:"wouldn't like = негативна форма. НЕ змінюється: he wouldn't like (не wouldn't likes).", topic:"would like"},
  {q:"Яка форма правильна для 'she' + would like?", opts:["She would likes to go","She will like to go","She would like to go","She would like go"], correct:2, note:"she would like — без -s! would like не змінюється для третьої особи.", topic:"would like"},
  {q:"'Він би хотів отримати підвищення цього року':", opts:["He would like to get a promotion","He would likes to get a promotion","He will like to get a promotion","He like to get a promotion"], correct:0, note:"would like + to + інфінітив. Для he/she — форма та сама, без -s.", topic:"would like"},
  {q:"'Де б ти хотів жити?' — правильно:", opts:["Where will you like to live?","Where you would like to live?","Where would you like to live?","Where do you would like to live?"], correct:2, note:"Питальне речення: Would + підмет + like + to + інфінітив. Where виноситься на початок.", topic:"would like"},
  {q:"'Ми б хотіли подякувати вам за допомогу':", opts:["We will like to thank you","We would like thank you","We would like to thank you","We would likes to thank you"], correct:2, note:"would like + to + дієслово. Не пропускай 'to' перед інфінітивом.", topic:"would like"},
  {q:"'Чи хотіла б вона приєднатися до нас на обід?':", opts:["Would she like to join us?","Will she like to join us?","She would like to join us?","Does she would like to join us?"], correct:0, note:"Питання: Would + підмет + like + to + інфінітив? Без 'will' і 'does'.", topic:"would like"},
  {q:"'Я б не хотів пропускати цю можливість':", opts:["I wouldn't like to miss this opportunity","I won't like to miss this opportunity","I wouldn't likes to miss this opportunity","I would not like missing this opportunity"], correct:0, note:"wouldn't like + to + інфінітив = негативна форма бажання.", topic:"would like"},
  {q:"'Вона б хотіла переїхати у більшу квартиру':", opts:["She would liked to move","She would like to move","She will like to move","She would likes to move"], correct:1, note:"would like — форма НЕ змінюється в залежності від часу. Завжди 'would like'.", topic:"would like"},
  {q:"'Що б ти хотів робити цими вихідними?':", opts:["What would you like do this weekend?","What would you like doing this weekend?","What would you like to do this weekend?","What will you like to do this weekend?"], correct:2, note:"would like + to + базова форма дієслова. Не 'doing', а 'to do'.", topic:"would like"},
  {q:"'Вони б не хотіли пропустити цю нагоду':", opts:["They wouldn't like to miss this chance","They won't like to miss this chance","They wouldn't likes to miss this chance","They would not like miss this chance"], correct:0, note:"They wouldn't like + to + інфінітив. Форма заперечення однакова для всіх осіб.", topic:"would like"},
  {q:"'Він би хотів тут бути' — чи змінюється форма для 'he'?", opts:["Так, треба 'would likes'","Ні, завжди 'would like'","Так, треба 'wills like'","Так, треба 'would liked'"], correct:1, note:"would like НІКОЛИ не змінюється! Однакова форма для I / you / he / she / they / we.", topic:"would like"},
  {q:"'Я б хотів надіслати вам звіт':", opts:["I would like to send you the report","I will like to send you the report","I would likes to send you the report","I would like send you the report"], correct:0, note:"would like + to + інфінітив. Не забудь 'to' перед send.", topic:"would like"},
  {q:"'Де б ти хотів попрацювати в майбутньому?' — виберіть правильне:", opts:["Where will you like to work?","Where would you like to work?","Where do you would like to work?","Where you would like to work?"], correct:1, note:"Where would you like to work? — класична форма питання з would like.", topic:"would like"},
  {q:"'Він би хотів почати нову роботу в понеділок':", opts:["He would like to start a new job on Monday","He would likes to start a new job on Monday","He will like to start a new job on Monday","He would like start a new job on Monday"], correct:0, note:"would like + to + інфінітив. Форма для he — без -s.", topic:"would like"},

  // --- be going to ---
  {q:"'Він збирається почати нову роботу' (план):", opts:["He will to start a new job","He is going to start a new job","He going to start a new job","He is go to start a new job"], correct:1, note:"be going to = запланована дія. He IS going to + інфінітив.", topic:"be going to"},
  {q:"'Ми збираємося переїхати наступного місяця':", opts:["We are going to move next month","We going to move next month","We will going to move next month","We are go to move next month"], correct:0, note:"We ARE going to + інфінітив. Дієслово 'be' погоджується з підметом.", topic:"be going to"},
  {q:"'Вона не збирається відвідувати зустріч':", opts:["She is not going to attend the meeting","She not going to attend the meeting","She is going not to attend the meeting","She doesn't going to attend the meeting"], correct:0, note:"Заперечення: is NOT going to + інфінітив. Не + doesn't.", topic:"be going to"},
  {q:"'Вони збираються оголосити результати завтра':", opts:["They are going to announce the results","They going to announce the results","They will going to announce","They are going announce the results"], correct:0, note:"They ARE going to + інфінітив. Не пропускай 'to' після 'going'.", topic:"be going to"},
  {q:"'Здається, зараз буде дощ!' (очевидно з ситуації):", opts:["It will rain!","It is going to rain!","It goes to rain!","It is going rain!"], correct:1, note:"be going to = очевидно з ситуації. Хмари зараз → It IS going to rain.", topic:"be going to"},
  {q:"'Твоя команда збирається завершити спринт вчасно?':", opts:["Will your team to finish the sprint?","Is your team going to finish the sprint on time?","Does your team going to finish the sprint?","Your team is going finish the sprint?"], correct:1, note:"Питання: Is/Are + підмет + going to + інфінітив?", topic:"be going to"},
  {q:"'Вона збирається презентувати проєкт директорам':", opts:["She is going to present her project","She going to present her project","She is go to present her project","She will going to present her project"], correct:0, note:"She IS going to + інфінітив. Дієслово 'be' узгоджується з she → is.", topic:"be going to"},
  {q:"'Ти збираєшся подаватися на цю посаду?':", opts:["Will you to apply for that position?","Are you going to apply for that position?","Do you going to apply for that position?","You are going apply for that position?"], correct:1, note:"Are you going to + інфінітив? — питальна форма з be going to.", topic:"be going to"},
  {q:"'Вони збираються запустити застосунок наступного тижня':", opts:["They are going to launch the app","They will going to launch the app","They going to launch the app","They are go to launch the app"], correct:0, note:"They ARE going to + інфінітив. Форма 'be' для they → are.", topic:"be going to"},
  {q:"'Я не збираюся більше сперечатися про це':", opts:["I am not going to argue about this","I not going to argue about this","I am going not to argue about this","I won't going to argue about this"], correct:0, note:"I am NOT going to + інфінітив = заперечна форма.", topic:"be going to"},
  {q:"'Він збирається запізнитися' — тип ситуації:", opts:["Спонтанне рішення → will","Запланована/очевидна дія → be going to","Звичка → Present Simple","Зараз відбувається → Present Continuous"], correct:1, note:"be going to = або план, або очевидна ситуація з поточних ознак.", topic:"be going to"},
  {q:"'Ми збираємося зробити перевірку коду в п'ятницю' (план):", opts:["We will have a code review on Friday","We are going to have a code review on Friday","We have going to a code review on Friday","We are going have a code review on Friday"], correct:1, note:"Запланована дія → be going to. We ARE going to + інфінітив.", topic:"be going to"},
  {q:"'Він збирається вивчати для іспиту на сертифікат':", opts:["He is going to study for the exam","He going to study for the exam","He is going study for the exam","He will going to study for the exam"], correct:0, note:"He IS going to + інфінітив. Для he/she/it → is going to.", topic:"be going to"},
  {q:"Чим відрізняється 'be going to' від 'will'?", opts:["Немає різниці","be going to — план/очевидне, will — спонтанне/передбачення","will — план, be going to — спонтанне","be going to — минуле, will — майбутнє"], correct:1, note:"be going to = запланована дія або очевидна з поточної ситуації. will = спонтанне рішення або передбачення.", topic:"be going to"},
  {q:"'Вона збирається вийти заміж?' — правильно:", opts:["Will she get married?","Is she going to get married?","Does she going to get married?","She is going get married?"], correct:1, note:"Is she going to + інфінітив? — питання про заплановану дію.", topic:"be going to"},
  {q:"'Я збираюся зателефонувати йому після обіду':", opts:["I'm going to call him after lunch","I go to call him after lunch","I will going to call him after lunch","I'm going call him after lunch"], correct:0, note:"I'm going to + інфінітив. 'I'm' = I am — скорочена форма.", topic:"be going to"},
  {q:"'Вони збираються переїхати у нову квартиру' — яке слово пропущено: They ___ going to move?", opts:["will","is","are","do"], correct:2, note:"They → ARE going to. Дієслово 'be' узгоджується з підметом: I am / he is / they are.", topic:"be going to"},
  {q:"'Вона не збирається відвідувати зустріч' — яке слово пропущено: She ___ not going to attend?", opts:["will","do","are","is"], correct:3, note:"She → IS not going to. Для she/he/it завжди is.", topic:"be going to"},
  {q:"'Дивись, зараз буде дощ!' — яка форма правильна для очевидної ситуації?", opts:["It will rain","It is going to rain","It rains","It is raining now"], correct:1, note:"Очевидна ситуація з поточних ознак → be going to. Бачимо хмари → It IS going to rain.", topic:"be going to"},
  {q:"'Я збираюся переглянути документацію' — яка форма?", opts:["I will going to read the docs","I am going to read the docs","I going to read the docs","I am go to read the docs"], correct:1, note:"I AM going to + інфінітив. Скорочено: I'm going to read the docs.", topic:"be going to"},

  // --- in order to / in order not to ---
  {q:"'Щоб прокинутися рано, він поставив будильник':", opts:["in order not to wake up early","in order to wake up early","in order wake up early","to order to wake up early"], correct:1, note:"in order TO + інфінітив = мета (щоб).", topic:"in order to"},
  {q:"'Щоб не запізнитися, вона залишила рано':", opts:["in order to not be late","in order not to be late","not in order to be late","in order to be not late"], correct:1, note:"in order NOT TO = щоб не. Порядок: not to завжди разом.", topic:"in order to"},
  {q:"'Щоб здати іспит, вона вивчає кожен день':", opts:["in order to pass the exam","in order not to pass the exam","in order to passing the exam","for to pass the exam"], correct:0, note:"in order to + інфінітив (базова форма). Не 'passing', а 'pass'.", topic:"in order to"},
  {q:"'Щоб не потрапити у пробку, він виїхав раніше':", opts:["in order to get stuck in traffic","in order not to get stuck in traffic","in order not getting stuck","in order to not get stuck"], correct:1, note:"in order not to + інфінітив = щоб не. NOT TO завжди стоять разом.", topic:"in order to"},
  {q:"'Щоб прискорити застосунок, ми додали кешування':", opts:["in order to speed up the app","in order not to speed up the app","in order to speeding up","in order for speed up the app"], correct:0, note:"in order to + інфінітив. Мета додавання кешування → прискорення.", topic:"in order to"},
  {q:"'Щоб не відволікатися, вона вимкнула телефон':", opts:["in order to not be distracted","in order not to be distracted","in order to be not distracted","not in order to be distracted"], correct:1, note:"in order NOT TO + інфінітив. not to завжди разом, не розривається.", topic:"in order to"},
  {q:"'Він читав документацію, щоб зрозуміти API':", opts:["in order to understand the API","in order understanding the API","for to understand the API","in order not to understand the API"], correct:0, note:"in order to + інфінітив (базова форма). 'understanding' — неправильно.", topic:"in order to"},
  {q:"'Вони працювали пізно, щоб встигнути до дедлайну':", opts:["in order to meet the deadline","in order not to meet the deadline","in order to meeting the deadline","in order for meet the deadline"], correct:0, note:"in order to + інфінітив = мета. meet the deadline = встигнути до дедлайну.", topic:"in order to"},
  {q:"'Щоб не робити помилок, він ставив запитання':", opts:["in order to not make mistakes","in order not to make mistakes","in order not making mistakes","in order to make no mistakes"], correct:1, note:"in order NOT TO + інфінітив = щоб не. NOT і TO не розриваються.", topic:"in order to"},
  {q:"'in order to' можна скоротити до:", opts:["for","just","to","so"], correct:2, note:"in order to = просто 'to'. Наприклад: He works hard to earn well. (скорочена форма)", topic:"in order to"},
  {q:"'Вона прийняла таксі, щоб не запізнитися' — скорочена форма:", opts:["She took a taxi in order not to be late","She took a taxi to not be late","She took a taxi not to be late","She took a taxi for not be late"], correct:2, note:"Скорочена форма: not to + інфінітив (без 'in order'). Обидва варіанти (з/без 'in order') правильні.", topic:"in order to"},
  {q:"'Щоб поліпшити процес, ми найняли консультанта':", opts:["in order to improve the process","in order not to improve the process","in order improving the process","for improving the process"], correct:0, note:"in order to + базова форма дієслова. 'improving' — неправильно після in order to.", topic:"in order to"},
  {q:"Яке слово ЗАВЖДИ стоїть після 'in order'?", opts:["for","to / not to","that","so"], correct:1, note:"in order TO + інфінітив або in order NOT TO + інфінітив. Завжди 'to' або 'not to'.", topic:"in order to"},
  {q:"'Він поставив запитання, щоб не помилитися':", opts:["He asked questions in order to make mistakes","He asked questions in order not to make mistakes","He asked questions in order to not making mistakes","He asked questions not in order to make mistakes"], correct:1, note:"in order NOT TO + інфінітив. NOT TO = щоб не.", topic:"in order to"},
  {q:"'Щоб зрозуміти вимоги, я написав нотатки':", opts:["in order to understand the requirements","in order not to understand the requirements","for to understand the requirements","in order to understanding the requirements"], correct:0, note:"in order to + базова форма дієслова.", topic:"in order to"},
  {q:"'Вона говорила тихо, щоб не розбудити дитину':", opts:["in order not to wake the baby","in order to wake the baby","in order to not wake up baby","not in order to wake the baby"], correct:0, note:"in order NOT TO + інфінітив. Тихо говорила — ПРИЧИНА (мета) — щоб не розбудити.", topic:"in order to"},
  {q:"'Я зробив нотатки, щоб нічого не забути':", opts:["in order to forget nothing","in order not to forget anything","in order not forget anything","in order to not forgetting"], correct:1, note:"in order NOT TO + інфінітив. 'not to forget' = щоб не забути.", topic:"in order to"},
  {q:"'Щоб рано встати, він поклав будильник' — яка конструкція тут?", opts:["in order not to","in order to","used to","be going to"], correct:1, note:"in order TO + інфінітив = мета. Поклав будильник → ЩОБ встати рано.", topic:"in order to"},
  {q:"'Він відмовився, щоб не пропустити рейс':", opts:["He refused in order to miss the flight","He refused in order not to miss the flight","He refused in order to not miss flight","He refused not in order to miss the flight"], correct:1, note:"in order NOT TO + інфінітив. Відмовився, щоб НЕ пропустити → not to miss.", topic:"in order to"},
  {q:"'Ми задокументували все, щоб допомогти наступному розробнику':", opts:["in order to help the next developer","in order not to help the next developer","in order help the next developer","for help the next developer"], correct:0, note:"in order to + інфінітив = мета. Документували → ЩОБ допомогти.", topic:"in order to"},

  // --- like the way / know how to ---
  {q:"'Мені подобається, як вона викладає англійську':", opts:["I like how she teaches English","I like that she teaches English","I like the way she teaches English","I like which she teaches English"], correct:2, note:"like the way = подобається, ЯК хтось щось робить. Саме 'the way', не 'how'.", topic:"like the way"},
  {q:"'Мені не подобається, як ти себе поводиш':", opts:["I don't like the way you behave","I don't like how you behave","I don't like that you behave","I don't like which you behave"], correct:0, note:"like the way + підмет + дієслово. 'the way' — ключова фраза.", topic:"like the way"},
  {q:"'Чи вмієш ти готувати?' — правильно:", opts:["Do you know how cook?","Do you know to cook?","Do you know how to cook?","Do you know cooking?"], correct:2, note:"know how to + інфінітив = знати ЯК щось робити. Не пропускай 'how' або 'to'.", topic:"like the way"},
  {q:"'Чи знає хтось, як танцювати?':", opts:["Does anybody know how to dance?","Does anybody know to dance?","Does anybody know how dance?","Does anybody knows how to dance?"], correct:0, note:"know how to + інфінітив. Для he/she/it → knows. Anybody → does anybody know.", topic:"like the way"},
  {q:"'Чому вона не вміє готувати?':", opts:["Why she doesn't know how to cook?","Why doesn't she know how to cook?","Why doesn't she know to cook?","Why she know not how to cook?"], correct:1, note:"Питання: Why doesn't she know how to cook? Порядок слів: Why + допоміжне + підмет + know how to + інфінітив.", topic:"like the way"},
  {q:"'Мені подобається, як він працює':", opts:["I like how he works","I like the way he works","I like that he works","Both A and B are correct"], correct:1, note:"Класична конструкція: like THE WAY + підмет + дієслово. Деякі кажуть 'how' але 'the way' — правильна форма для цього курсу.", topic:"like the way"},
  {q:"'Ти вмієш керувати цим інструментом?':", opts:["Do you know how to use this tool?","Do you know how use this tool?","Do you know to use this tool?","Do you know using this tool?"], correct:0, note:"know how to + інфінітив. Не 'how use' і не 'to use' окремо.", topic:"like the way"},
  {q:"'Він не вміє плавати':", opts:["He doesn't know how to swim","He doesn't know how swim","He doesn't know to swim","He don't know how to swim"], correct:0, note:"He doesn't know how to swim. Для he → doesn't. know how to + інфінітив.", topic:"like the way"},
  {q:"'Мені подобається, як вона посміхається':", opts:["I like her smile","I like the way she smiles","I like how she smiles","I like that she smiles"], correct:1, note:"like the way + підмет + дієслово = подобається, ЯК хтось щось робить.", topic:"like the way"},
  {q:"'Вона не знає, як вирішити цю проблему':", opts:["She doesn't know how solve this problem","She doesn't know how to solve this problem","She doesn't know to solve this problem","She don't know how to solve this problem"], correct:1, note:"know how to + інфінітив. Не пропускай 'to' після 'how'.", topic:"like the way"},

  // --- Possessive Case ---
  {q:"'Ім'я дівчини' — як сказати правильно?", opts:["the name of girl","the girl name","the girl's name","the name's girl"], correct:2, note:"Одушевлені іменники → 's. Дівчина — жива, тому the girl's name.", topic:"Possessive Case"},
  {q:"'Дах будинку' — правильний варіант:", opts:["the house's roof","the roof's house","the house roof","the roof of the house"], correct:3, note:"Неодушевлені іменники → of. Будинок — неживий, тому the roof OF the house.", topic:"Possessive Case"},
  {q:"'Хвіст кота' — правильно:", opts:["the tail of the cat","the cat tail","the cat's tail","the cats tail"], correct:2, note:"Кіт — одушевлений → 's. The cat's tail.", topic:"Possessive Case"},
  {q:"'Вчорашня газета' — яка форма правильна?", opts:["the newspaper of yesterday","the yesterday's newspaper","yesterday's newspaper","newspaper of yesterday"], correct:2, note:"Часові вирази → 's. yesterday's newspaper (не потрібен артикль 'the').", topic:"Possessive Case"},
  {q:"'Двері машини' — неодушевлений предмет:", opts:["the car's door","the door of the car","the car door","the door's car"], correct:1, note:"Машина — неодушевлена → of. The door OF the car.", topic:"Possessive Case"},
  {q:"'Книга мого друга' — правильно:", opts:["a friend's book of mine","a book of my friend","a book of my friend's","my friend book"], correct:2, note:"a book of my friend's = my friend's book. Подвійний присвійний — правильна конструкція.", topic:"Possessive Case"},
  {q:"'Ім'я нашої компанії' — правильно:", opts:["the company's name","the name of the company","both are correct","the companies's name"], correct:2, note:"Для організацій можна використовувати і 's, і 'of'. Обидва варіанти правильні.", topic:"Possessive Case"},
  {q:"'Кімната Марії' — правильно:", opts:["the room of Mary","Mary room","Mary's room","Marys room"], correct:2, note:"Власні імена — одушевлені → 's. Mary's room.", topic:"Possessive Case"},
  {q:"'Робота тижня' (тижнева робота) — правильно:", opts:["the week work","the week's work","the work of the week","week's of work"], correct:1, note:"Часовий вираз → 's. A week's work, a day's holiday.", topic:"Possessive Case"},
  {q:"'Центр міста' — неодушевлений предмет:", opts:["the city's center","the center of the city","both are correct","the city center's"], correct:2, note:"Місця і організації можуть вживатися з обома формами. The city's center і the center of the city — обидва правильні.", topic:"Possessive Case"},
  {q:"'Кришка пляшки':", opts:["the bottle's cap","the cap of the bottle","both are correct","the bottles cap"], correct:1, note:"Пляшка — неодушевлена → of. The cap OF the bottle.", topic:"Possessive Case"},
  {q:"'Мій друг' — як сказати через 'a friend of':", opts:["a friend of my","a friend of mine","a friend of me","my friend of"], correct:1, note:"a friend of mine = my friend. Після 'of' використовують присвійний займенник: mine, yours, his, hers, ours, theirs.", topic:"Possessive Case"},

  // --- Verbs + Infinitive ---
  {q:"'Вона вирішила поїхати до Лондона':", opts:["She decided going to London","She decided to go to London","She decided go to London","She decided to going London"], correct:1, note:"decide + TO + інфінітив. Це одне з дієслів групи Verbs + Infinitive.", topic:"Verbs + Infinitive"},
  {q:"'Він відмовився вчитися':", opts:["He refused studying","He refused to study","He refused study","He refuses to studying"], correct:1, note:"refuse + TO + інфінітив. Усі дієслова цієї групи: pretend/decide/refuse/agree/fail/manage/try/hope/plan/learn/forget + TO.", topic:"Verbs + Infinitive"},
  {q:"'Вона погодилася прийти':", opts:["She agreed coming","She agreed to come","She agreed come","She agreed to coming"], correct:1, note:"agree + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Йому не вдалося здати іспит':", opts:["He failed to pass the exam","He failed passing the exam","He failed pass the exam","He failed to passing the exam"], correct:0, note:"fail + TO + інфінітив = не вийшло зробити.", topic:"Verbs + Infinitive"},
  {q:"'Я сподіваюся побачити тебе незабаром':", opts:["I hope seeing you soon","I hope to see you soon","I hope see you soon","I hope to seeing you soon"], correct:1, note:"hope + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Ми плануємо подорожувати наступного місяця':", opts:["We plan travelling next month","We plan to travel next month","We plan travel next month","We plan to travelling next month"], correct:1, note:"plan + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Вона намагалася залишатися спокійною':", opts:["She tried being calm","She tried to be calm","She tried be calm","She tries to being calm"], correct:1, note:"try + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Вона навчилася плавати у п'ять років':", opts:["She learned swimming at five","She learned to swim at five","She learned swim at five","She learned to swimming at five"], correct:1, note:"learn + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Він забув зателефонувати їй':", opts:["He forgot calling her","He forgot to call her","He forgot call her","He forgot to calling her"], correct:1, note:"forget + TO + інфінітив = забути зробити (дія не виконана).", topic:"Verbs + Infinitive"},
  {q:"Яке дієслово НЕ входить у групу Verbs + Infinitive?", opts:["decide","enjoy","refuse","manage"], correct:1, note:"enjoy + -ing (gerund): I enjoy swimming. Усі інші (decide/refuse/manage тощо) → + TO + інфінітив.", topic:"Verbs + Infinitive"},
  {q:"'Вони погодилися зустрітися завтра':", opts:["They agreed to meet tomorrow","They agreed meeting tomorrow","They agreed meet tomorrow","They agree to meeting tomorrow"], correct:0, note:"agree + TO + інфінітив. Форма минулого часу: agreed.", topic:"Verbs + Infinitive"},
  {q:"'Їй вдалося взяти вихідний' — яке дієслово тут?", opts:["She managed to get a day off","She succeeded to get a day off","She failed to get a day off","She tried to get a day off"], correct:0, note:"managed to = вдалося зробити. succeeded звазвичай вживається з in + gerund.", topic:"Verbs + Infinitive"},

  // --- Two Verbs in a Row ---
  {q:"'She ___ to go.' — яка форма першого дієслова?", opts:["wanting","to want","wants","want to"], correct:2, note:"Перше дієслово змінюється (wants — третя особа однини). Друге — базова форма: to go.", topic:"Two Verbs"},
  {q:"'He ___ to leave' (минулий час):", opts:["decided","decides","to decide","deciding"], correct:0, note:"Перше дієслово бере мин. час: decided. Друге — базова форма: to leave.", topic:"Two Verbs"},
  {q:"'They ___ to answer' (заперечення в минулому):", opts:["didn't refused","refused","refused to","refused not"], correct:1, note:"They refused to answer. Перше дієслово = refused (змінено). Друге = to answer (базова).", topic:"Two Verbs"},
  {q:"'She ___ to finish on time' — яке слово пропущено (мин. час)?", opts:["manage","managed","managing","to manage"], correct:1, note:"managed (мин. час) + to finish (базова форма). Перше дієслово несе весь граматичний зміст.", topic:"Two Verbs"},
  {q:"Яке правило діє, коли в реченні два дієслова підряд?", opts:["Обидва в інфінітиві","Перше змінюється, друге — базова форма","Друге змінюється, перше — базова форма","Обидва змінюються"], correct:1, note:"ПЕРШЕ дієслово змінюється (час, особа). ДРУГЕ залишається в базовій формі (інфінітив).", topic:"Two Verbs"},
  {q:"'He hopes ___ her.' — яка форма другого дієслова?", opts:["seeing","see","to see","seen"], correct:2, note:"Після hope → to + інфінітив. He hopes TO SEE her. Друге дієслово = to see.", topic:"Two Verbs"},
  {q:"'Why did he fail ___ help?' — що пропущено?", opts:["helping","help","to help","helped"], correct:2, note:"fail + TO + інфінітив. Did fail → to help. Перше дієслово (did fail) уже несе час.", topic:"Two Verbs"},

  // --- Adjectives + Prepositions ---
  {q:"'Задоволений результатами' — який прийменник?", opts:["satisfied in the results","satisfied about the results","satisfied with the results","satisfied of the results"], correct:2, note:"satisfied WITH something. Запам'ятай: satisfied WITH, disappointed IN, afraid OF.", topic:"Adjectives + Prepositions"},
  {q:"'Боюся павуків' — який прийменник?", opts:["afraid from spiders","afraid of spiders","afraid about spiders","afraid with spiders"], correct:1, note:"afraid OF something/somebody. Порівняй: scared OF (теж правильно).", topic:"Adjectives + Prepositions"},
  {q:"'Пишаюся тобою' — який прийменник?", opts:["proud about you","proud of you","proud in you","proud with you"], correct:1, note:"proud OF somebody/something. I'm proud OF you.", topic:"Adjectives + Prepositions"},
  {q:"'Схвильований зустріччю' — який прийменник?", opts:["excited about the meeting","excited of the meeting","excited from the meeting","excited with the meeting"], correct:0, note:"excited ABOUT something. Excited about = схвильований, в очікуванні.", topic:"Adjectives + Prepositions"},
  {q:"'Стурбований його результатами' — який прийменник?", opts:["concerned of his results","concerned in his results","concerned about his results","concerned with his results"], correct:2, note:"concerned ABOUT something. I am concerned ABOUT his results.", topic:"Adjectives + Prepositions"},
  {q:"'Готовий до іспиту' — який прийменник?", opts:["ready about the exam","ready of the exam","ready for the exam","ready to the exam"], correct:2, note:"ready FOR something. Are you ready FOR the exam?", topic:"Adjectives + Prepositions"},
  {q:"'Розчарований у ній' — який прийменник?", opts:["disappointed with her","disappointed in her","disappointed about her","disappointed of her"], correct:1, note:"disappointed IN somebody. Але: disappointed WITH something (результатом).", topic:"Adjectives + Prepositions"},
  {q:"'Відповідальний за проєкт' — який прийменник?", opts:["responsible of the project","responsible about the project","responsible to the project","responsible for the project"], correct:3, note:"responsible FOR something. I am responsible FOR the project.", topic:"Adjectives + Prepositions"},
  {q:"'Захоплений нею' — який прийменник з 'fascinated'?", opts:["fascinated by her","fascinated of her","fascinated with her","fascinated about her"], correct:0, note:"fascinated BY somebody/something. BY вживається з багатьма прикметниками почуттів.", topic:"Adjectives + Prepositions"},
  {q:"'Злий на нього' — який прийменник з 'angry'?", opts:["angry of him","angry with him","angry about him","angry to him"], correct:1, note:"angry WITH somebody (злий на людину). angry ABOUT something (злий через ситуацію).", topic:"Adjectives + Prepositions"},

  // --- Question Words ---
  {q:"'Де вона живе?' — правильний порядок слів:", opts:["Where she lives?","Where lives she?","Where does she live?","Where do she live?"], correct:2, note:"Питальне слово + допоміжне (does/did/is) + підмет + дієслово. Where DOES she LIVE?", topic:"Question Words Structure"},
  {q:"'Коли він приїхав?' — правильно:", opts:["When he arrived?","When arrived he?","When did he arrive?","When did he arrived?"], correct:2, note:"When + did + підмет + базова форма. When DID he ARRIVE? (не arrived)", topic:"Question Words Structure"},
  {q:"'Чому ти запізнився?' — правильно:", opts:["Why you are late?","Why are you late?","Why you late?","Why do you are late?"], correct:1, note:"Why + are + you + late? Допоміжне be переходить на початок після питального слова.", topic:"Question Words Structure"},
  {q:"'Скільки книг у неї є?' — правильно:", opts:["How many books she has?","How many books does she have?","How many books has she?","How many books she does have?"], correct:1, note:"How many + іменник + does + підмет + базова форма дієслова.", topic:"Question Words Structure"},
  {q:"'Хто прийде на вечірку?' — правильно:", opts:["Who is coming to the party?","Who does come to the party?","Who comes to the party?","Who will coming to the party?"], correct:0, note:"Who is coming? — запитання про підмет з Present Continuous або Who comes? — Present Simple. Обидва можливі, але Who IS COMING? природніше.", topic:"Question Words Structure"},
  {q:"'Як часто вона ходить до спортзалу?' — правильно:", opts:["How often she goes to the gym?","How often does she go to the gym?","How often does she goes to the gym?","How often she does go?"], correct:1, note:"How often + does + підмет + базова форма. How often DOES she GO?", topic:"Question Words Structure"},
  {q:"'Чому вони не відповіли?' — правильно:", opts:["Why they didn't answer?","Why didn't they answer?","Why they did not answered?","Why did they not answered?"], correct:1, note:"Why + didn't + підмет + базова форма. Why DIDN'T they ANSWER?", topic:"Question Words Structure"},

  // --- Reflexive Pronouns ---
  {q:"'Вона зшила собі новий костюм':", opts:["She made her a new suit","She made herself a new suit","She made hers a new suit","She made by herself a new suit"], correct:1, note:"herself = зворотний займенник (для себе). Без BY = для себе / сам виконав дію.", topic:"Reflexive Pronouns"},
  {q:"'Не вдар себе!':", opts:["Don't hurt you!","Don't hurt yourself!","Don't hurt by yourself!","Don't hurt oneself!"], correct:1, note:"yourself = зворотний займенник (до 'you'). Don't hurt YOURSELF!", topic:"Reflexive Pronouns"},
  {q:"'Вони зробили це самі, без допомоги':", opts:["They did it themselves","They did it by themselves","They did it theirselves","A і B правильні"], correct:3, note:"themselves = вони самі (виконавці дії). BY themselves = самі, без чиєїсь допомоги. Обидва варіанти можливі залежно від контексту.", topic:"Reflexive Pronouns"},
  {q:"'Частуйтесь!' (їжте самі, беріть) — як сказати?", opts:["Help yourselves!","Help yourself! (до одного)","Обидва правильні залежно від кількості","Help by yourself!"], correct:2, note:"Help yourself! (одна людина) / Help yourselves! (кілька людей). Обидві форми правильні.", topic:"Reflexive Pronouns"},
  {q:"'Подивися на себе!' — правильно:", opts:["Look at you!","Look at yourself!","Look by yourself!","Look yourself!"], correct:1, note:"Look AT yourself! Зворотний займенник після прийменника at.", topic:"Reflexive Pronouns"},
  {q:"'Він вивчив іспанську сам, без учителя' — яка форма?", opts:["He learned Spanish himself","He learned Spanish by himself","He learned Spanish hisself","He learned by himself Spanish"], correct:1, note:"BY himself = без чиєїсь допомоги, самостійно. himself (без BY) = він сам зробив це (а не хтось інший).", topic:"Reflexive Pronouns"},
  {q:"Яке зворотне займенник для 'we'?", opts:["weselves","ourself","ourselves","itself"], correct:2, note:"Зворотні займенники: myself, yourself, himself, herself, itself, OURSELVES, yourselves, themselves.", topic:"Reflexive Pronouns"},
  {q:"'Вона себе поранила' — правильно:", opts:["She hurted herself","She hurt herself","She hurt hers","She hurted hers"], correct:1, note:"She hurt herself. hurt — неправильне дієслово: hurt/hurt/hurt (всі форми однакові).", topic:"Reflexive Pronouns"},

  // --- Agreement: So / Neither ---
  {q:"'Я теж щаслива' після 'She is happy':", opts:["So do I","Neither am I","So am I","I am also happy"], correct:2, note:"Після СТВЕРДЖУВАЛЬНОГО з BE: So + am/is/are + підмет. She IS happy → So AM I.", topic:"Agreement"},
  {q:"'Він теж не вміє плавати' після 'She can't swim':", opts:["So can he","Neither can he","Neither he can","He also can't"], correct:1, note:"Після ЗАПЕРЕЧНОГО: Neither + допоміжне + підмет. Can't → Neither CAN he.", topic:"Agreement"},
  {q:"'Я теж' після 'I am tired':", opts:["So am I","So do I","Neither am I","Me too (офіційно)"], correct:0, note:"Після стверджувального з BE → So am/is/are + підмет. I AM tired → So AM I.", topic:"Agreement"},
  {q:"'Вона теж не курить' після 'He doesn't smoke':", opts:["So doesn't she","Neither does she","Neither she does","So does she neither"], correct:1, note:"Після заперечного: Neither + does/did + підмет. Doesn't → Neither DOES she.", topic:"Agreement"},
  {q:"'Ми теж сьогодні не готові' після 'She is not ready today':", opts:["So are we","Neither are we","Neither we are","Not are we"], correct:1, note:"Після заперечного з BE: Neither + am/is/are + підмет. She is NOT ready → Neither ARE we.", topic:"Agreement"},
  {q:"'Він теж завжди робить нотатки' після 'She always takes notes':", opts:["So does he","So he does","Neither does he","So do he"], correct:0, note:"Після стверджувального: So + does/do + підмет. Takes → does → So DOES he.", topic:"Agreement"},
  {q:"Після якого речення використовується 'Neither + допоміжне + підмет'?", opts:["Після стверджувального","Після заперечного","Після питального","Після будь-якого"], correct:1, note:"Neither + допоміжне + підмет = я теж НЕ... Лише після ЗАПЕРЕЧНИХ речень.", topic:"Agreement"},
  {q:"'Я теж не здивований' — альтернативна форма:", opts:["Neither am I surprised","I am not surprised either","Both are correct","So am I not surprised"], correct:2, note:"Обидва варіанти правильні: Neither am I. / I am not surprised either.", topic:"Agreement"},
  {q:"'Я теж втомився' після 'He is tired':", opts:["Neither am I","So am I","So do I","I am tired too (офіційно)"], correct:1, note:"Після стверджувального з BE: So AM I. He IS tired → So AM I.", topic:"Agreement"},
  {q:"'Вона теж не готова' після 'He is not ready':", opts:["So is she","Neither is she","Neither she is","So not is she"], correct:1, note:"Після заперечного: Neither IS she. He is NOT ready → Neither IS she.", topic:"Agreement"},

  // --- Connectors: Both/Either/Neither ---
  {q:"'Або ти йдеш, або я' — правильна конструкція:", opts:["Both you go and I go","Neither you go nor I go","Either you go or I go","Not only you go but also I go"], correct:2, note:"either … or … = або … або … (вибір між двома варіантами).", topic:"Connectors"},
  {q:"'У нього немає ні часу, ні грошей':", opts:["He has both no time and money","He has either no time or money","He has neither time nor money","He has not only time but money"], correct:2, note:"neither … nor … = ні … ні … (жоден із двох).", topic:"Connectors"},
  {q:"'Він не тільки відповідальний, але й добрий':", opts:["He both responsible and kind","He either responsible or kind","He neither responsible nor kind","He is not only responsible but also kind"], correct:3, note:"not only … but also … = не тільки … але й … Обидві якості присутні.", topic:"Connectors"},
  {q:"'Вони наступного року і працюватимуть, і вчитимуться':", opts:["They either work or study next year","They not only work but study next year","They will both work and study next year","They neither work nor study next year"], correct:2, note:"both … and … = і … і … (обидві дії). Порівняй: either/or = вибір, neither/nor = жоден.", topic:"Connectors"},
  {q:"'Або він, або вона підуть' — правильно:", opts:["Both he and she will go","Either he or she will go","Neither he nor she will go","Not only he but she will go"], correct:1, note:"either … or … = або … або … (один із двох).", topic:"Connectors"},
  {q:"'Вона і добре співає, і добре танцює':", opts:["She either sings or dances well","She neither sings nor dances well","She both sings and dances well","She not only sings but dances well"], correct:2, note:"both … and … = і … і … (обидві дії рівною мірою виконуються).", topic:"Connectors"},
  {q:"Яка конструкція означає 'ні ... ні ...'?", opts:["both … and","either … or","neither … nor","not only … but also"], correct:2, note:"neither … nor … = ні … ні … Жоден із двох варіантів.", topic:"Connectors"},
  {q:"Яка конструкція означає 'або ... або ...'?", opts:["both … and","either … or","neither … nor","not only … but also"], correct:1, note:"either … or … = або … або … Вибір одного з двох.", topic:"Connectors"},
  {q:"'Він не тільки розумний, але й добрий' — яка конструкція?", opts:["both … and","either … or","neither … nor","not only … but also"], correct:3, note:"not only … but also … = не тільки … але й … Підкреслює обидві якості.", topic:"Connectors"},

  // --- Discourse Markers ---
  {q:"'Відверто кажучи, я не був готовий' — правильна фраза:", opts:["Clearly speaking,","Frankly speaking,","Honest speaking,","True speaking,"], correct:1, note:"Frankly speaking = відверто кажучи. Це стала фраза-зв'язка.", topic:"Discourse Markers"},
  {q:"'Справа в тому, що у нас немає часу':", opts:["The matter is that we have no time","The point is that we have no time","The case is that we have no time","The thing that we have no time"], correct:0, note:"The matter is that… = справа в тому, що… Стала конструкція для пояснення причини.", topic:"Discourse Markers"},
  {q:"'Тим не менш, він нам допоміг':", opts:["Nevermind, he helped us","Nevertheless, he helped us","However ever, he helped us","Notwithstanding he helped us"], correct:1, note:"Nevertheless = тим не менш. Вживається для контрасту.", topic:"Discourse Markers"},
  {q:"'Крім того, вони часто подорожують разом':", opts:["Besides, they often travel together","Moreover that, they travel","Furthermore, although they travel","Apart, they often travel"], correct:0, note:"Besides = крім того, до того ж. Вживається для додавання інформації.", topic:"Discourse Markers"},
  {q:"'За його словами, ми запізнимося':", opts:["According to him, we will be late","Due to him, we will be late","Thanks to him, we will be late","Regarding him, we will be late"], correct:0, note:"According to = за словами / згідно з. According TO him.", topic:"Discourse Markers"},
  {q:"'Завдяки їй, все пройшло добре':", opts:["Because of her, everything went well","According to her, everything went well","Thanks to her, everything went well","Due to her, everything went well"], correct:2, note:"Thanks to = завдяки (позитивний результат). Because of = через (нейтрально або негативно).", topic:"Discourse Markers"},
  {q:"'Через дощ ми залишилися вдома':", opts:["Thanks to the rain, we stayed home","According to the rain, we stayed home","Because of the rain, we stayed home","In spite of the rain, we stayed home"], correct:2, note:"because of = через / із-за (причина, часто негативна). Thanks to = завдяки (позитивна причина).", topic:"Discourse Markers"},
  {q:"'На жаль, він пропустив рейс':", opts:["Frankly speaking, he missed the flight","Apparently, he missed the flight","Unfortunately, he missed the flight","Nevertheless, he missed the flight"], correct:2, note:"Unfortunately = на жаль. Вживається для вираження жалю.", topic:"Discourse Markers"},
  {q:"'Що стосується мене, я надаю перевагу чаю':", opts:["As about me, I prefer tea","As for me, I prefer tea","For me about, I prefer tea","About me, I prefer tea"], correct:1, note:"As for me = що стосується мене / щодо мене. Стала фраза.", topic:"Discourse Markers"},
  {q:"'На відміну від своєї сестри, вона дуже тиха':", opts:["Unlikely her sister, she is quiet","Unlike her sister, she is very quiet","Opposite her sister, she is quiet","Different from her sister is quiet"], correct:1, note:"Unlike = на відміну від. Unlike + іменник/займенник.", topic:"Discourse Markers"},
  {q:"'З одного боку, це ризиковано. З іншого боку, це шанс':", opts:["From one hand… from other hand…","On the one hand… on the other hand…","One one hand… another hand…","At one hand… at other hand…"], correct:1, note:"On the one hand… on the other hand… — стала конструкція для протиставлення.", topic:"Discourse Markers"},

  // --- scared vs afraid ---
  {q:"'Я зараз злякався!' (щось злякало прямо зараз):", opts:["I'm afraid!","I'm scared!","I fear!","I'm frighten!"], correct:1, note:"scared = страх у конкретний момент (прямо зараз). afraid = загальний або про майбутнє.", topic:"scared vs afraid"},
  {q:"'Боюся, він може запізнитися завтра' (припущення):", opts:["I'm scared he will be late","I'm afraid he can be late","I fear he will be late","I'm frightened he is late"], correct:1, note:"afraid = для припущень і загального страху про майбутнє. scared = поточний момент.", topic:"scared vs afraid"},
  {q:"'Ти боїшся темряви?' (загальне):", opts:["Are you scared of the dark?","Are you afraid of the dark?","Both are correct","Are you fear of dark?"], correct:2, note:"Для постійного/загального страху обидва слова можливі: afraid of / scared of.", topic:"scared vs afraid"},
  {q:"Яке слово краще вживати для ПОТОЧНОГО переляку?", opts:["afraid","scared","frightened","fear"], correct:1, note:"scared = конкретний момент. I'm scared! — щось налякало прямо зараз.", topic:"scared vs afraid"},
  {q:"Яке слово краще для ПРИПУЩЕННЯ або ЗАГАЛЬНОГО страху?", opts:["scared","afraid","terrified","panic"], correct:1, note:"afraid = загальний або для припущень. I'm afraid he can be late.", topic:"scared vs afraid"},
];

